In [2]:
pip install numpy pandas scikit-learn seaborn jupyter

Note: you may need to restart the kernel to use updated packages.


Question 1: Pandas version

In [3]:
import pandas as pd
pd.__version__

# Pandas Version = 2.2.2

'2.2.2'

Question 2: Records count

In [4]:
# Read the CSV file into a Pandas DataFrame

df = pd.read_csv("laptops.csv")

# Total number of rows
total_rows = len(df)
total_rows

# Total number of rows = 2160

2160

Question 3: Laptop brands

In [5]:
# To find the number of laptop brands, we need to find the number of unique records in the 'Laptop' column

unique_laptop_brands = df['Brand'].nunique()
unique_laptop_brands

# Laptop brands = 27

27

Question 4: Missing values

In [6]:
# Check for missing values in each column
missing_values = df.isnull().sum()
missing_values

# Columns with missing values = 3

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

Question 5: Maximum final price

In [7]:
df[df['Brand'] == 'Dell']['Final Price'].max()

# Maximum Final Price of Dell notebooks = 7150.47

3936.0

Question 6: Median value of Screen

In [14]:
df['Screen'].median() # Median = 15.6
df['Screen'].mode()   # Mode = 15.6

# Fill in missing values with mode value (15.6)
df['Screen'].fillna(15.6, inplace=True)

/var/folders/dj/5j3pnl4d6n3f8brtqgllmlp00000gn/T/ipykernel_6464/2716349142.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Screen'].fillna(15.6, inplace=True)


In [15]:
df['Screen'].median()
# Median did not change

15.6

Question 7: Sum of weights

In [52]:
import numpy as np

# 1. Select all the "Innjoo" laptops from the dataset
df[df['Brand'] == 'Innjoo']

# 2. Select only columns RAM, Storage, Screen
df[df['Brand'] == 'Innjoo'][['RAM', 'Storage', 'Screen']]

# 3. Get the underlying NumPy array. Let's call it x
x = df[df['Brand'] == 'Innjoo'][['RAM', 'Storage', 'Screen']].to_numpy()
print(x)

# 4. Compute matrix-matrix multiplication between the transpose of x and x
xtx = x.T @ x
print(xtx)

# 5. Compute the inverse of xtx
inverse_xtx = np.linalg.inv(xtx)
print(inverse_xtx)

# 6. Create an array y with values [1100, 1300, 800, 900, 1000, 1100]
y = np.array([1100, 1300, 800, 900, 1000, 1100])
print(y)

# 7. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
inverse_times_transpose = inverse_xtx @ x.T
w = inverse_times_transpose @ y
print(w)
print(sum(w))

[[  8.  256.   15.6]
 [  8.  512.   15.6]
 [  4.   64.   14.1]
 [  6.   64.   14.1]
 [  6.  128.   14.1]
 [  6.  128.   14.1]]
[[2.52000e+02 8.32000e+03 5.59800e+02]
 [8.32000e+03 3.68640e+05 1.73952e+04]
 [5.59800e+02 1.73952e+04 1.28196e+03]]
[[ 2.78025381e-01 -1.51791334e-03 -1.00809855e-01]
 [-1.51791334e-03  1.58286725e-05  4.48052175e-04]
 [-1.00809855e-01  4.48052175e-04  3.87214888e-02]]
[1100 1300  800  900 1000 1100]
[45.58076606  0.42783519 45.29127938]
91.2998806299557
